language: python
python:
- 2.7
- 3.6
# Check that all template lines from the skeleton project have been removed.
#   Do NOT remove this when customising your project.
before_install: ['! grep -R SKELETON | grep -v grep']
install:
- pip install -r requirements-dev.txt
- pip install coveralls tox-travis
script:
- tox -e verify
after_script:
- tox -e lint
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
  user: amc6010
  # supply password with `travis encrypt --add deploy.password`
  distributions: dists
after_success:
- coveralls
cache: pip
before_script:
  # Disable IPv6. Ref travis-ci/travis-ci#8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
