language: python
python:
- 2.7
- 3.6
# Check that all template lines from the skeleton project have been removed.
#   Do NOT remove this when customising your project.
before_install: ['! grep -R SKELETON | grep -v grep']
install:
- pip install -r requirements-dev.txt
- pip install coveralls pytest-cov
script:
- python setup.py checkdocs
- py.test --cov SKELETON test_SKELETON.py  # SKELETON: For single module only.
- py.test --cov SKELETON/ tests/           # SKELETON: For multi-module only.
- py.test README.rst docs/*.rst docs/api/*.rst
- sphinx-build -W docs/ build/docs/
- pylint --disable=W SKELETON.py  # SKELETON: For single module only.
- pylint --disable=W SKELETON/    # SKELETON: For multi-module only.
after_script:
- flake8
- pycodestyle
- pylint SKELETON.py  # SKELETON: For single module only.
- pylint SKELETON/    # SKELETON: For multi-module only.
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
  user: amc6010
  # supply password with `travis encrypt --add deploy.password`
  distributions: dists
after_success:
- coveralls
cache: pip
before_script:
  # Disable IPv6. Ref travis-ci/travis-ci#8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
