dist: bionic
language: python
python:
- 2.7
- &latest_py3 3.6
# Check that all template lines from the skeleton project have been removed.
#   Do NOT remove this when customising your project.
before_install: ['! grep -R SKELETON | grep -v grep']
install:
- pip install -r requirements-dev.txt
- pip install -U --upgrade-strategy=eager coveralls tox tox-travis
script:
- tox
branches:
  except:
  - skeleton
jobs:
  include:
  - stage: docs-and-lint
    python: *latest_py3
    install: pip install tox
    script:
      - tox -e black
      - tox -e docs
    after_script: tox -e lint
    after_success: []
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    provider: pypi
    server: https://upload.pypi.org/legacy/
    on:
      tags: true
      all_branches: true
    user: amc6010
    # supply password with `travis encrypt --add deploy.password`
    distributions: dists
after_success:
- coveralls
cache: pip
before_script:
  # Enable IPv6. Ref travis-ci/travis-ci#8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
